services:
  - type: web
    name: flaskwebhub
    runtime: python
    runtimeVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 4 --worker-class sync --timeout 120 --bind 0.0.0.0:8080 main:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        scope: PROJECT
      - key: SESSION_SECRET
        scope: PROJECT
    autoDeploy: true
    staticPublicPath: /static
    routes:
      - type: http
        path: /
